language: julia

jobs:
  include:
    - stage: "Testing"
      julia: 1.5.3
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.instantiate()'
        - julia test/mps_test.jl
        - julia test/tebd_test.jl
      after_success: skip
