language: julia

jobs:
  include:
    - stage: "Testing"
      julia: 1.5.3
      os: linux
      script:
        - ls
        - ls test/
        - julia test/mps_test.jl
        - julia test/tebd_test.jl
      after_success: skip
